/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author zeina
 */
public class RegulatorGUI extends javax.swing.JFrame {
    private final UserController userController;
    private Regulator currentRegulator;

    /**
     * Creates new form RegulatorGUI
     */
    public RegulatorGUI() {
        this.userController = AppContext.userController();
        initComponents();
        configureDefaults();
        populateFromUserController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegulatorID = new javax.swing.JTextField();
        txtAgencyName = new javax.swing.JTextField();
        cmbAccessLevel = new javax.swing.JComboBox<>();
        txtAuditRegion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtProductID = new javax.swing.JTextField();
        txtTrackingRecordID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAuditNotes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbActivityType = new javax.swing.JComboBox<>();
        cmbRecordStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReportSummary = new javax.swing.JTextArea();
        btnAuditActivity = new javax.swing.JButton();
        btnViewTracking = new javax.swing.JButton();
        btnReviewStorage = new javax.swing.JButton();
        btnVerifyCompliance = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Regulator Management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Audit, Compliance and Tracking Control");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Regulator Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel3.setText("Regulator ID");

        jLabel4.setText("Agency Name");

        jLabel5.setText("Access Level: ");

        jLabel6.setText("Audit Region: ");

        cmbAccessLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Senior Regulator", "Regional Auditor", "Viewer" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAuditRegion))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegulatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegulatorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAuditRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Audit Review", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 153, 51))); // NOI18N

        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });

        txtTrackingRecordID.setText(" ");
        txtTrackingRecordID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrackingRecordIDActionPerformed(evt);
            }
        });

        txtAuditNotes.setColumns(20);
        txtAuditNotes.setRows(5);
        jScrollPane1.setViewportView(txtAuditNotes);

        jLabel7.setText("Product ID");

        jLabel8.setText("Order ID");

        jLabel10.setText("Audit Notes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(30, 30, 30))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txtTrackingRecordID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrackingRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tracking & Compliance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 255, 204));

        cmbActivityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supply Chain Activity", "Tracking Records", "Storage Record", "Compliance Verification", "Audit Report" }));

        cmbRecordStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "Reviewed", "Approved", "Flagged", "Closed" }));

        jLabel11.setText("Activity Type");

        jLabel12.setText("Record Status");

        jLabel13.setText("Report Summary");

        txtReportSummary.setColumns(20);
        txtReportSummary.setRows(5);
        jScrollPane2.setViewportView(txtReportSummary);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRecordStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRecordStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAuditActivity.setBackground(new java.awt.Color(21, 101, 192));
        btnAuditActivity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAuditActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnAuditActivity.setText("Audit Activity ");
        btnAuditActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditActivityActionPerformed(evt);
            }
        });

        btnViewTracking.setBackground(new java.awt.Color(0, 172, 193));
        btnViewTracking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewTracking.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTracking.setText("View Tracking");
        btnViewTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTrackingActionPerformed(evt);
            }
        });

        btnReviewStorage.setBackground(new java.awt.Color(255, 152, 0));
        btnReviewStorage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReviewStorage.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewStorage.setText("Review Storage ");
        btnReviewStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewStorageActionPerformed(evt);
            }
        });

        btnVerifyCompliance.setBackground(new java.awt.Color(76, 175, 80));
        btnVerifyCompliance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerifyCompliance.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyCompliance.setText("Verify Compliance");
        btnVerifyCompliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyComplianceActionPerformed(evt);
            }
        });

        btnGenerateReport.setBackground(new java.awt.Color(106, 27, 154));
        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAuditActivity)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnViewTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGenerateReport))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnReviewStorage)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnVerifyCompliance))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnClear)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBack)
                                        .addGap(125, 125, 125))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuditActivity)
                    .addComponent(btnViewTracking)
                    .addComponent(btnReviewStorage)
                    .addComponent(btnVerifyCompliance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTrackingRecordIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrackingRecordIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrackingRecordIDActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void btnAuditActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditActivityActionPerformed
        try {
            int regulatorID = parseRequiredInt(txtRegulatorID.getText(), "Regulator ID");
            String agencyName = readRequiredText(txtAgencyName.getText(), "Agency Name");
            String accessLevel = (String) cmbAccessLevel.getSelectedItem();
            String auditRegion = readRequiredText(txtAuditRegion.getText(), "Audit Region");

            User baseUser = resolveLoggedInUser();
            if (baseUser == null) {
                throw new IllegalStateException("No logged-in user was found in UserController.");
            }

            if (regulatorID != baseUser.getUserID()) {
                throw new IllegalArgumentException("Regulator ID must match the logged-in user ID.");
            }

            Regulator regulator = new Regulator(
                    regulatorID,
                    agencyName,
                    accessLevel,
                    auditRegion,
                    baseUser.getUserID(),
                    baseUser.getName(),
                    baseUser.getEmail(),
                    baseUser.getPassword(),
                    baseUser.getRole()
            );

            currentRegulator = regulator;
            regulator.auditSupplyChainActivity();
            txtAuditNotes.setText("Audit activity executed for " + agencyName + " in " + auditRegion + ".");
            JOptionPane.showMessageDialog(this,
                    "Audit activity executed successfully.",
                    "Audit Activity",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error while auditing activity.",
                    "Regulator Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAuditActivityActionPerformed

    private void btnViewTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTrackingActionPerformed
        try {
            int orderID = parseRequiredInt(txtTrackingRecordID.getText(), "Order ID");
            Order order = AppContext.orderController().getOrderByID(orderID);
            if (order == null) {
                throw new IllegalArgumentException("Order not found.");
            }

            Regulator regulator = ensureRegulator();
            regulator.viewTrackingRecords(order);
            String trackingInfo = order.trackOrder();
            txtAuditNotes.setText(trackingInfo);
            JOptionPane.showMessageDialog(this,
                    trackingInfo,
                    "Tracking Records",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error while viewing tracking.",
                    "Regulator Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewTrackingActionPerformed

    private void btnReviewStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewStorageActionPerformed
        try {
            String productID = readRequiredText(txtProductID.getText(), "Product ID");
            Regulator regulator = ensureRegulator();
            regulator.reviewStorageRecord(productID);
            txtAuditNotes.setText("Storage reviewed for product " + productID + ".");
            JOptionPane.showMessageDialog(this,
                    "Storage record reviewed successfully.",
                    "Storage Review",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error while reviewing storage.",
                    "Regulator Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReviewStorageActionPerformed

    private void btnVerifyComplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyComplianceActionPerformed
        try {
            Regulator regulator = ensureRegulator();
            String activityType = (String) cmbActivityType.getSelectedItem();
            String recordStatus = (String) cmbRecordStatus.getSelectedItem();
            String notes = txtAuditNotes.getText() == null ? "" : txtAuditNotes.getText().trim();

            if (notes.isBlank()) {
                notes = "No audit notes provided.";
            }

            String summary = "Compliance verified for " + activityType
                    + " with status " + recordStatus
                    + ". Notes: " + notes;

            txtReportSummary.setText(summary);
            cmbRecordStatus.setSelectedItem("Reviewed");
            JOptionPane.showMessageDialog(this,
                    summary,
                    "Compliance Verification",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error while verifying compliance.",
                    "Regulator Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerifyComplianceActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        try {
            Regulator regulator = ensureRegulator();
            Report report = regulator.generateAuditReport();
            txtReportSummary.setText(report.toString());
            JOptionPane.showMessageDialog(this,
                    report.toString(),
                    "Generated Report",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error while generating report.",
                    "Regulator Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRegulatorID.setText("");
        txtAgencyName.setText("");
        txtAuditRegion.setText("");
        txtProductID.setText("");
        txtTrackingRecordID.setText("");
        txtAuditNotes.setText("");
        txtReportSummary.setText("");
        cmbAccessLevel.setSelectedIndex(0);
        cmbActivityType.setSelectedIndex(0);
        cmbRecordStatus.setSelectedIndex(0);
        currentRegulator = null;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            User currentUser = AppContext.getCurrentUser();
            javax.swing.JFrame dashboard = currentUser == null
                    ? new LoginGuii(AppContext.authBoundary())
                    : AppContext.createDashboardForRole(currentUser.getRole());

            if (dashboard == null) {
                throw new IllegalStateException("No screen is mapped for the current role.");
            }

            dashboard.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Navigation Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void configureDefaults() {
        txtRegulatorID.setText("");
        txtAgencyName.setText("");
        txtAuditRegion.setText("");
        txtProductID.setText("");
        txtTrackingRecordID.setText("");
        txtAuditNotes.setText("");
        txtReportSummary.setText("");
    }

    private Regulator ensureRegulator() {
        if (currentRegulator != null) {
            return currentRegulator;
        }

        int regulatorID = parseRequiredInt(txtRegulatorID.getText(), "Regulator ID");
        String agencyName = readRequiredText(txtAgencyName.getText(), "Agency Name");
        String accessLevel = (String) cmbAccessLevel.getSelectedItem();
        String auditRegion = readRequiredText(txtAuditRegion.getText(), "Audit Region");

        User baseUser = resolveLoggedInUser();
        if (baseUser == null) {
            throw new IllegalStateException("No logged-in user was found in UserController.");
        }

        if (regulatorID != baseUser.getUserID()) {
            throw new IllegalArgumentException("Regulator ID must match the logged-in user ID.");
        }

        currentRegulator = new Regulator(
                regulatorID,
                agencyName,
                accessLevel,
                auditRegion,
                baseUser.getUserID(),
                baseUser.getName(),
                baseUser.getEmail(),
                baseUser.getPassword(),
                baseUser.getRole()
        );
        return currentRegulator;
    }

    private void populateFromUserController() {
        User baseUser = resolveLoggedInUser();
        if (baseUser == null) {
            return;
        }

        txtRegulatorID.setText(String.valueOf(baseUser.getUserID()));
        txtAgencyName.setText(baseUser.getName());
        if (baseUser.getRole() != null) {
            for (int i = 0; i < cmbAccessLevel.getItemCount(); i++) {
                if (baseUser.getRole().equalsIgnoreCase(cmbAccessLevel.getItemAt(i))) {
                    cmbAccessLevel.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private User resolveLoggedInUser() {
        User currentUser = AppContext.getCurrentUser();
        if (currentUser == null) {
            return null;
        }

        User storedUser = userController.getUser(currentUser.getUserID());
        return storedUser != null ? storedUser : currentUser;
    }

    private int parseRequiredInt(String value, String fieldName) {
        String text = value == null ? "" : value.trim();
        if (text.isBlank() || text.startsWith("jTextField")) {
            throw new IllegalArgumentException(fieldName + " cannot be empty.");
        }

        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(fieldName + " must be a valid number.");
        }
    }

    private String readRequiredText(String value, String fieldName) {
        String text = value == null ? "" : value.trim();
        if (text.isBlank() || text.startsWith("jTextField")) {
            throw new IllegalArgumentException(fieldName + " cannot be empty.");
        }
        return text;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(RegulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegulatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditActivity;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnReviewStorage;
    private javax.swing.JButton btnVerifyCompliance;
    private javax.swing.JButton btnViewTracking;
    private javax.swing.JComboBox<String> cmbAccessLevel;
    private javax.swing.JComboBox<String> cmbActivityType;
    private javax.swing.JComboBox<String> cmbRecordStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAgencyName;
    private javax.swing.JTextArea txtAuditNotes;
    private javax.swing.JTextField txtAuditRegion;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtRegulatorID;
    private javax.swing.JTextArea txtReportSummary;
    private javax.swing.JTextField txtTrackingRecordID;
    // End of variables declaration//GEN-END:variables
}

