/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class shipmentGuii extends javax.swing.JFrame {

    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
    private final ShipmentBoundary shipmentBoundary;
    private Integer currentOrderId;
    private Integer currentShipmentId;
    private final String launchMode;

    /**
     * Creates new form shipmentGuii
     */
    public shipmentGuii() {
        this(AppContext.shipmentBoundary(), null, null, null);
    }

    public shipmentGuii(ShipmentBoundary shipmentBoundary, Shipment shipment, Integer orderId, String launchMode) {
        this.shipmentBoundary = shipmentBoundary == null ? AppContext.shipmentBoundary() : shipmentBoundary;
        this.launchMode = launchMode == null ? "create" : launchMode;
        this.currentOrderId = orderId;
        initComponents();
        wireActions();
        if (shipment != null) {
            applyShipmentToForm(shipment);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtShipmentID = new javax.swing.JTextField();
        txtOrigin = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDistance = new javax.swing.JLabel();
        txtDepartureDate = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtArrivalDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbShipmentStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCurrentLocation = new javax.swing.JTextField();
        btnCreateShipment = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JTextField();
        btnUpdateLocation = new javax.swing.JButton();
        btnUpdateConditions = new javax.swing.JButton();
        btnCalculateETA = new javax.swing.JButton();
        btnMarkDelivered = new javax.swing.JButton();
        btnValidateData = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTemperature = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtHumidity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConditionNotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Shipment Route");

        jLabel2.setText("Shipment ID");

        jLabel3.setText("Origin");

        jLabel4.setText("Destination");

        jLabel5.setText("Current Location");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 255));
        jLabel6.setText("Shipment Details");

        jLabel7.setText("Weight (kg)");

        txtDistance.setText("Distance (km)");

        txtDepartureDate.setText("Departure Date");

        jLabel10.setText("Arrival Date");

        jLabel11.setText("Shipment status");

        cmbShipmentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Created", "In Transit", "Received", "Delivered", "Delayed", "Cancelled" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDepartureDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDistance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbShipmentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtArrivalDate))
                                .addGap(2, 2, 2))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtDistance))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cmbShipmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartureDate))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setText("Current Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtShipmentID)
                            .addComponent(txtOrigin)
                            .addComponent(txtDestination)
                            .addComponent(txtCurrentLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 121, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtShipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCreateShipment.setBackground(new java.awt.Color(33, 150, 243));
        btnCreateShipment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateShipment.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateShipment.setText("Create Shipment");

        btnUpdateStatus.setBackground(new java.awt.Color(156, 39, 176));
        btnUpdateStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("   Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnUpdateLocation.setBackground(new java.awt.Color(0, 172, 193));
        btnUpdateLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLocation.setText("Update Location");

        btnUpdateConditions.setBackground(new java.awt.Color(255, 152, 0));
        btnUpdateConditions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateConditions.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateConditions.setText("Update Location");

        btnCalculateETA.setBackground(new java.awt.Color(76, 175, 80));
        btnCalculateETA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculateETA.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculateETA.setText("Calculate ETA");
        btnCalculateETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateETAActionPerformed(evt);
            }
        });

        btnMarkDelivered.setBackground(new java.awt.Color(46, 125, 50));
        btnMarkDelivered.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMarkDelivered.setForeground(new java.awt.Color(255, 255, 255));
        btnMarkDelivered.setText("Mark Delivered");
        btnMarkDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkDeliveredActionPerformed(evt);
            }
        });

        btnValidateData.setBackground(new java.awt.Color(121, 85, 72));
        btnValidateData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidateData.setForeground(new java.awt.Color(255, 255, 255));
        btnValidateData.setText("Vaildate Date");

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("Shipment Managament");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condition Monitoring", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(102, 204, 0))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Humidity"));

        txtHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHumidityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel12.setText("Condition Notes");

        txtConditionNotes.setColumns(20);
        txtConditionNotes.setForeground(new java.awt.Color(153, 153, 153));
        txtConditionNotes.setRows(5);
        txtConditionNotes.setText("All items are within acceptable temperature and humidity range.");
        jScrollPane1.setViewportView(txtConditionNotes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCreateShipment, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculateETA))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnMarkDelivered)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnValidateData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateShipment)
                    .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLocation)
                    .addComponent(btnUpdateConditions)
                    .addComponent(btnCalculateETA))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarkDelivered)
                    .addComponent(btnValidateData)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHumidityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHumidityActionPerformed

    private void wireActions() {
        btnCreateShipment.addActionListener(evt -> handleCreateShipment());
        btnUpdateLocation.addActionListener(evt -> handleUpdateLocation());
        btnUpdateConditions.addActionListener(evt -> handleUpdateConditions());
        btnValidateData.addActionListener(evt -> handleValidateData());
        btnClear.addActionListener(evt -> handleClear());
        btnBack.addActionListener(evt -> handleBack());
        cmbShipmentStatus.addActionListener(evt -> syncStatusField());
    }

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        try {
            int shipmentID = requireShipmentID();
            String status = resolveStatusText();
            shipmentBoundary.updateShipmentStatus(shipmentID, status);
            Shipment shipment = shipmentBoundary.loadShipment(shipmentID);
            applyShipmentToForm(shipment);
            JOptionPane.showMessageDialog(this, "Shipment status updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnMarkDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkDeliveredActionPerformed
        try {
            int shipmentID = requireShipmentID();
            shipmentBoundary.markDelivered(shipmentID);
            Shipment shipment = shipmentBoundary.loadShipment(shipmentID);
            applyShipmentToForm(shipment);
            JOptionPane.showMessageDialog(this, "Shipment marked as delivered.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Delivery Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMarkDeliveredActionPerformed

    private void btnCalculateETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateETAActionPerformed
        try {
            int shipmentID = requireShipmentID();
            java.util.Date eta = shipmentBoundary.calculateEta(shipmentID);
            txtArrivalDate.setText(formatDate(eta));
            Shipment shipment = shipmentBoundary.loadShipment(shipmentID);
            applyShipmentToForm(shipment);
            JOptionPane.showMessageDialog(this, "ETA calculated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ETA Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateETAActionPerformed

    private void handleCreateShipment() {
        try {
            Shipment shipment = buildShipmentFromFields();
            int orderID = resolveOrderID();
            Shipment saved = shipmentBoundary.saveShipment(orderID, shipment);
            currentOrderId = saved.getOrderID();
            currentShipmentId = saved.getShipmentID();
            applyShipmentToForm(saved);
            JOptionPane.showMessageDialog(this, "Shipment saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Create Shipment Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleUpdateLocation() {
        try {
            int shipmentID = requireShipmentID();
            String location = readRequiredText(txtCurrentLocation.getText(), "Current Location");
            shipmentBoundary.updateShipmentLocation(shipmentID, location);
            Shipment shipment = shipmentBoundary.loadShipment(shipmentID);
            applyShipmentToForm(shipment);
            JOptionPane.showMessageDialog(this, "Location updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Location Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleUpdateConditions() {
        try {
            int shipmentID = requireShipmentID();
            double temperature = readRequiredDouble(txtTemperature.getText(), "Temperature");
            double humidity = readRequiredDouble(txtHumidity.getText(), "Humidity");
            String notes = txtConditionNotes.getText();
            shipmentBoundary.updateShipmentConditions(shipmentID, temperature, humidity, notes);
            Shipment shipment = shipmentBoundary.loadShipment(shipmentID);
            applyShipmentToForm(shipment);
            JOptionPane.showMessageDialog(this, "Condition data updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Condition Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleValidateData() {
        try {
            validateFormData();
            JOptionPane.showMessageDialog(this, "Shipment data looks valid.", "Validation", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void handleClear() {
        txtShipmentID.setText("");
        txtOrigin.setText("");
        txtDestination.setText("");
        txtCurrentLocation.setText("");
        txtWeight.setText("");
        jTextField6.setText("");
        txtArrivalDate.setText("");
        jTextField7.setText("");
        txtTemperature.setText("");
        txtHumidity.setText("");
        txtConditionNotes.setText("");
        cmbShipmentStatus.setSelectedIndex(0);
        btnUpdateStatus.setText("");
        currentShipmentId = null;
    }

    private void handleBack() {
        new LoginGuii(AppContext.authBoundary()).setVisible(true);
        dispose();
    }

    private void syncStatusField() {
        Object selected = cmbShipmentStatus.getSelectedItem();
        if (selected != null) {
            btnUpdateStatus.setText(selected.toString());
        }
    }

    private void applyShipmentToForm(Shipment shipment) {
        if (shipment == null) {
            return;
        }

        currentShipmentId = shipment.getShipmentID() > 0 ? shipment.getShipmentID() : currentShipmentId;
        currentOrderId = shipment.getOrderID() > 0 ? shipment.getOrderID() : currentOrderId;

        txtShipmentID.setText(shipment.getShipmentID() > 0 ? String.valueOf(shipment.getShipmentID()) : "");
        txtOrigin.setText(nullToEmpty(shipment.getOrigin()));
        txtDestination.setText(nullToEmpty(shipment.getDestination()));
        txtCurrentLocation.setText(nullToEmpty(shipment.getCurrentLocation()));
        txtWeight.setText(shipment.getWeight() > 0 ? String.valueOf(shipment.getWeight()) : "");
        jTextField6.setText(shipment.getDistance() > 0 ? String.valueOf(shipment.getDistance()) : "");
        jTextField7.setText(formatDate(shipment.getDepartureDate()));
        txtArrivalDate.setText(formatDate(shipment.getArrivalDate()));
        txtTemperature.setText(shipment.getTemperature() == 0 ? "" : String.valueOf(shipment.getTemperature()));
        txtHumidity.setText(shipment.getHumidity() == 0 ? "" : String.valueOf(shipment.getHumidity()));
        txtConditionNotes.setText(nullToEmpty(shipment.getConditionNotes()));
        setComboSelection(normalizeStatus(shipment.getStatus()));
        btnUpdateStatus.setText(nullToEmpty(shipment.getStatus()));
    }

    private Shipment buildShipmentFromFields() throws ParseException {
        Shipment shipment = new Shipment();

        String shipmentIDText = txtShipmentID.getText().trim();
        if (!shipmentIDText.isEmpty()) {
            int shipmentID = Integer.parseInt(shipmentIDText);
            if (shipmentID > 0) {
                shipment.setShipmentID(shipmentID);
            }
        }

        shipment.setOrigin(readRequiredText(txtOrigin.getText(), "Origin"));
        shipment.setDestination(readRequiredText(txtDestination.getText(), "Destination"));
        shipment.setCurrentLocation(readRequiredText(txtCurrentLocation.getText(), "Current Location"));
        shipment.setWeight(readRequiredDouble(txtWeight.getText(), "Weight"));
        shipment.setDistance(readRequiredDouble(jTextField6.getText(), "Distance"));
        shipment.setDepartureDate(parseDate(readRequiredText(jTextField7.getText(), "Departure Date")));

        String arrivalText = txtArrivalDate.getText().trim();
        if (!arrivalText.isEmpty()) {
            shipment.setArrivalDate(parseDate(arrivalText));
        }

        String temperatureText = txtTemperature.getText().trim();
        if (!temperatureText.isEmpty()) {
            shipment.setTemperature(Double.parseDouble(temperatureText));
        }

        String humidityText = txtHumidity.getText().trim();
        if (!humidityText.isEmpty()) {
            shipment.setHumidity(Double.parseDouble(humidityText));
        }

        shipment.setConditionNotes(txtConditionNotes.getText());
        shipment.setStatus(resolveStatusText());

        if (currentOrderId != null && currentOrderId > 0) {
            shipment.setOrderID(currentOrderId);
        }

        return shipment;
    }

    private void validateFormData() throws ParseException {
        readRequiredText(txtOrigin.getText(), "Origin");
        readRequiredText(txtDestination.getText(), "Destination");
        readRequiredText(txtCurrentLocation.getText(), "Current Location");
        readRequiredDouble(txtWeight.getText(), "Weight");
        readRequiredDouble(jTextField6.getText(), "Distance");
        parseDate(readRequiredText(jTextField7.getText(), "Departure Date"));

        String arrivalText = txtArrivalDate.getText().trim();
        if (!arrivalText.isEmpty()) {
            parseDate(arrivalText);
        }
    }

    private int requireShipmentID() {
        Integer shipmentID = readOptionalInteger(txtShipmentID.getText());
        if (shipmentID == null || shipmentID <= 0) {
            throw new IllegalArgumentException("Shipment ID is required.");
        }
        return shipmentID;
    }

    private int resolveOrderID() {
        if (currentOrderId != null && currentOrderId > 0) {
            return currentOrderId;
        }

        throw new IllegalArgumentException("Order ID is required to save the shipment.");
    }

    private String resolveStatusText() {
        String manualStatus = btnUpdateStatus.getText() == null ? "" : btnUpdateStatus.getText().trim();
        if (!manualStatus.isEmpty()) {
            return manualStatus;
        }

        Object selected = cmbShipmentStatus.getSelectedItem();
        return selected == null ? "Pending" : selected.toString();
    }

    private Integer readOptionalInteger(String value) {
        if (value == null || value.trim().isEmpty()) {
            return null;
        }

        return Integer.parseInt(value.trim());
    }

    private String readRequiredText(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException(fieldName + " cannot be empty.");
        }

        return value.trim();
    }

    private double readRequiredDouble(String value, String fieldName) {
        String trimmed = readRequiredText(value, fieldName);
        double parsed = Double.parseDouble(trimmed);
        if (parsed <= 0) {
            throw new IllegalArgumentException(fieldName + " must be greater than 0.");
        }
        return parsed;
    }

    private java.util.Date parseDate(String value) throws ParseException {
        synchronized (DATE_FORMAT) {
            return DATE_FORMAT.parse(value.trim());
        }
    }

    private String formatDate(java.util.Date date) {
        if (date == null) {
            return "";
        }

        synchronized (DATE_FORMAT) {
            return DATE_FORMAT.format(date);
        }
    }

    private void setComboSelection(String status) {
        if (status == null || status.isBlank()) {
            return;
        }

        for (int i = 0; i < cmbShipmentStatus.getItemCount(); i++) {
            String item = cmbShipmentStatus.getItemAt(i);
            if (item != null && item.equalsIgnoreCase(status)) {
                cmbShipmentStatus.setSelectedIndex(i);
                return;
            }
        }
    }

    private String normalizeStatus(String status) {
        if (status == null) {
            return "Pending";
        }

        String normalized = status.trim().replace('_', ' ').toLowerCase();
        if (normalized.contains("in transit")) {
            return "In Transit";
        }
        if (normalized.contains("out for delivery")) {
            return "Out for Delivery";
        }
        if (normalized.contains("deliver")) {
            return "Delivered";
        }
        if (normalized.contains("delay")) {
            return "Delayed";
        }
        if (normalized.contains("cancel")) {
            return "Cancelled";
        }
        if (normalized.contains("created") || normalized.contains("pending")) {
            return "Pending";
        }

        return status;
    }

    private String nullToEmpty(String value) {
        return value == null ? "" : value;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shipmentGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shipmentGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shipmentGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shipmentGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shipmentGuii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculateETA;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateShipment;
    private javax.swing.JButton btnMarkDelivered;
    private javax.swing.JButton btnUpdateConditions;
    private javax.swing.JButton btnUpdateLocation;
    private javax.swing.JTextField btnUpdateStatus;
    private javax.swing.JButton btnValidateData;
    private javax.swing.JComboBox<String> cmbShipmentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtArrivalDate;
    private javax.swing.JTextArea txtConditionNotes;
    private javax.swing.JTextField txtCurrentLocation;
    private javax.swing.JLabel txtDepartureDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JLabel txtDistance;
    private javax.swing.JTextField txtHumidity;
    private javax.swing.JTextField txtOrigin;
    private javax.swing.JTextField txtShipmentID;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
